name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      -
jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Builds and Starts
        run: |
          docker-compose up -d

      - name: Run Integration Tests
        run: |
          docker-compose up -d
          docker exec realworld_drash deno test -A --unstable tests/integration/test.ts

      - name: Run Unit Tests
        run: |
          docker-compose up -d
          docker exec realworld_drash deno test -A --unstable tests/unit/models/base_model_test.ts

  linter:
      # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Formatter
        run: deno fmt --check --unstable --ignore='src/public,src/vue,src/package.json,src/webpack.config.js'

      - name: Linter
        run: deno lint --unstable --ignore='src/public,src/vue,src/package.json,src/webpack.config.js'
        
    - name: Test with pytest
      run: |
        pytest --alluredir=allure-results
        
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure-history: allure-history
        keep_reports: 920
        
    - name: Deploy Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
        
