name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release_drafter_config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.CI_USER_PAT }}
  
  - name: Test with pytest
      run: |
        pytest --alluredir=allure-results
        
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure-history: allure-history
        keep_reports: 920
        
    - name: Deploy Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
        
